/**
 * Created by Administrator on 2019/3/11.
 */
export default {
    REDUX_INIT:"persist/REHYDRATE",
    THEME_CHANGE:"THEME_CHANGE",
    THEME_INIT:"THEME_INIT",
    USER_LOGOUT:"USER_LOGOUT",
    USER_LOGIN:"USER_LOGIN",
    CAR_REFRESH:"CAR_REFRESH",
    CAR_REFRESH_SUCCESS:"CAR_REFRESH_SUCCESS",
    CAR_REFRESH_FAIL:"CAR_REFRESH_FAIL",
    CAR_LOAD_MORE:"CAR_LOAD_MORE",
    CAR_LOAD_MORE_SUCCESS:"CAR_LOAD_MORE_SUCCESS",
    CAR_LOAD_MORE_FAIL:"CAR_LOAD_MORE_FAIL",
    CAR_LOAD_DETAIL:'CAR_LOAD_DETAIL',
    NETWORK_CHANGE:"NETWORK_CHANGE",
    KAHANG_REFRESH:"KAHANG_REFRESH",
    KAHANG_REFRESH_SUCCESS:"KAHANG_REFRESH_SUCCESS",
    KAHANG_REFRESH_FAIL:"KAHANG_REFRESH_FAIL",
    KAHANG_LOAD_MORE:"KAHANG_LOAD_MORE",
    KAHANG_LOAD_MORE_SUCCESS:"KAHANG_LOAD_MORE_SUCCESS",
    KAHANG_LOAD_MORE_FAIL:"KAHANG_LOAD_MORE_FAIL",
    KAHANG_LOAD_PREVIEW:'KAHANG_LOAD_PREVIEW',
}